# Generated by Django 5.2.5 on 2025-10-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='get_a_quote',
            field=models.CharField(choices=[('erp', 'ERP Solutions'), ('outsourcing', 'IT Outsourcing'), ('managed', 'Managed IT Services'), ('analytics', 'Data & Analytics'), ('general', 'General Enquiry')], default='general', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='project_timeline',
            field=models.CharField(choices=[('1-2 weeks', '1–2 Weeks'), ('1-2 months +', '1–2 Months +'), ('flexible', 'Flexible')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(choices=[('implementation', 'New ERP Implementation'), ('integration', 'ERP Integration with Existing Systems'), ('customization', 'ERP Customization or Module Development'), ('maintenance', 'ERP Maintenance / Support'), ('migration', 'ERP Data Migration or Upgrade'), ('dedicated', 'Dedicated IT Team / Staff Augmentation'), ('helpdesk', 'Helpdesk / Technical Support Setup'), ('infrastructure', 'Infrastructure Management'), ('full-outsource', 'Full IT Department Outsourcing'), ('project', 'Short-term Project Outsourcing'), ('network', 'Network Monitoring and Maintenance'), ('server', 'Server Management'), ('cloud', 'Cloud Infrastructure Management'), ('security', 'Cybersecurity and Compliance'), ('backup', 'Backup and Disaster Recovery'), ('dashboard', 'Business Intelligence Dashboard Setup'), ('predictive', 'Predictive Analytics Model'), ('ml', 'Machine Learning Integration'), ('pipeline', 'Data Cleaning / Pipeline Setup'), ('ai', 'AI Chatbot / Automation System')], default='General Enquiry', max_length=50),
        ),
    ]
