# Generated by Django 5.2.7 on 2025-10-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('get_a_quote', models.CharField(choices=[('yes', 'Get a Quote'), ('no', 'General Enquiry')], max_length=10)),
                ('service', models.CharField(choices=[('ERP', 'ERP Implementation'), ('IT', 'IT outsourcing'), ('MS', 'Managed Services'), ('Data&AI', 'Data Analytics & AI'), ('Other', 'Other')], max_length=50)),
                ('project_timeline', models.CharField(choices=[('1week', '1-2 Weeks'), ('3months', '1 Month+'), ('flexible', 'Flexible')], max_length=20)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
