# Generated by Django 5.2.7 on 2025-10-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactmessage_get_a_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='get_a_quote',
            field=models.CharField(choices=[('ERP Solutions', 'ERP Solutions'), ('IT Outsourcing', 'IT Outsourcing'), ('Managed IT Services', 'Managed IT Services'), ('Data & Analytics', 'Data & Analytics'), ('general', 'General Enquiry')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(choices=[('New ERP Implementation', 'New ERP Implementation'), ('ERP Integration with Existing Systems', 'ERP Integration with Existing Systems'), ('ERP Customization or Module Development', 'ERP Customization or Module Development'), ('ERP Maintenance / Support', 'ERP Maintenance / Support'), ('ERP Data Migration or Upgrade', 'ERP Data Migration or Upgrade'), ('Dedicated IT Team / Staff Augmentation', 'Dedicated IT Team / Staff Augmentation'), ('Helpdesk / Technical Support Setup', 'Helpdesk / Technical Support Setup'), ('Infrastructure Management', 'Infrastructure Management'), ('Full IT Department Outsourcing', 'Full IT Department Outsourcing'), ('Short-term Project Outsourcing', 'Short-term Project Outsourcing'), ('Network Monitoring and Maintenance', 'Network Monitoring and Maintenance'), ('Server Management', 'Server Management'), ('Cloud Infrastructure Management', 'Cloud Infrastructure Management'), ('Cybersecurity and Compliance', 'Cybersecurity and Compliance'), ('Backup and Disaster Recovery', 'Backup and Disaster Recovery'), ('Business Intelligence Dashboard Setup', 'Business Intelligence Dashboard Setup'), ('Predictive Analytics Model', 'Predictive Analytics Model'), ('Machine Learning Integration', 'Machine Learning Integration'), ('Data Cleaning / Pipeline Setup', 'Data Cleaning / Pipeline Setup'), ('AI Chatbot / Automation System', 'AI Chatbot / Automation System')], default='General Enquiry', max_length=50),
        ),
    ]
