# Generated by Django 5.2.5 on 2025-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('enterprise_stack', 'Enterprise Stack'), ('ops_automation', 'Ops & Automation'), ('ai_intelligence', 'AI & Intelligence'), ('security_trust', 'Security & Trust'), ('digital_playbooks', 'Digital Playbooks'), ('future_signals', 'Future Signals'), ('inside_brandevia', 'Inside Brandevia')], default='enterprise_stack', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default='ERP', max_length=50),
        ),
    ]
