# Generated by Django 5.2.5 on 2025-12-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_category_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.JSONField(default=list),
        ),
    ]
