# Generated by Django 5.2.5 on 2025-12-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_tag_blogpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('enterprise_stack', 'Enterprise Stack'), ('ops_automation', 'Ops & Automation'), ('ai_intelligence', 'AI & Intelligence'), ('security_trust', 'Security & Trust'), ('digital_playbooks', 'Digital Playbooks'), ('future_signals', 'Future Signals'), ('inside_brandevia', 'Inside Brandevia')], default='enterprise_stack'),
        ),
    ]
