# Generated by Django 5.2.7 on 2025-10-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingList',
            new_name='MailingListSubscriber',
        ),
    ]
